routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\AddressController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
Route::get('order',[OrderController::class,'index'])->name('order');
Route::get('order/{order}',[OrderController::class,'show'])->name('order.details');
Route::get('/addresses/{order}', [AddressController::class, 'index'])->name('addresses.index');
Route::any('/pay/{order}', [OrderController::class, 'pay'])->name('pay');
Route::any('/verify', [OrderController::class, 'verify'])->name('user.payment_verify');

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;

    protected $table = "cities";
    protected $guarded = [];
}

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $table = "orders";
    protected $guarded = [];

    public function getPaymentTypeAttribute($paymentType)
    {
        switch($paymentType){
            case 'pos' :
                $paymentType = 'دستگاه pos';
                break;
            case 'online' :
                $paymentType = 'اینترنتی';
                break;
        }
        return $paymentType;
    }

    public function getPaymentStatusAttribute($paymentStatus)
    {
        switch($paymentStatus){
            case '0' :
                $paymentStatus = 'در انتظار پرداخت';
                break;
            case '1' :
                $paymentStatus = 'پرداخت شده';
                break;
            case '2' :
                $paymentStatus = 'پرداخت ناموفق';
                break;
        }
        return $paymentStatus;
    }

    public function orderItems()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function address()
    {
        return $this->belongsTo(UserAddress::class);
    }
}

app/Models/OrderItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
    use HasFactory;

    protected $table = "order_items";
    protected $guarded = [];

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory;

    protected $table = "products";
    protected $guarded = [];



    public function getIsActiveAttribute($is_active)
    {
        return $is_active ? 'فعال' : 'غیرفعال';
    }

}

app/Models/Province.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Province extends Model
{
    use HasFactory;

    protected $table = "provinces";
    protected $guarded = [];


}

app/Models/Transaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Transaction extends Model
{
    use HasFactory;

    protected $table = "transactions";
    protected $guarded = [];

    public function getStatusAttribute($status)
    {
        switch ($status) {
            case '0':
                $status = 'ناموفق';
                break;
            case '1':
                $status = 'موفق';
                break;
        }
        return $status;
    }

    public function scopeGetData($query, $month, $status)
    {
        $v = verta()->startMonth()->subMonth($month - 1);
        $date = verta()->getGregorian($v->year, $v->month, $v->day);
        return $query->where('created_at', '>', Carbon::create($date[0], $date[1], $date[2], 0, 0, 0))
            ->where('status', $status)
            ->get();
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'avatar',
        'provider_name',
        'email_verified_at',
        'otp',
        'cellphone',
        'login_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function rates()
    {
        return $this->hasMany(ProductRate::class);
    }
}

app/Models/UserAddress.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserAddress extends Model
{
    use HasFactory;

    protected $table = "user_addresses";
    protected $guarded = [];

    function province_name($provinceId)
    {
        return Province::findOrFail($provinceId)->name;
    }

    function city_name($cityId)
    {
        return City::findOrFail($cityId)->name;
    }
}

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use App\Models\City;
use App\Models\Order;
use App\Models\Province;
use App\Models\UserAddress;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Order $order)
    {
        $addresses = UserAddress::where('user_id', 1)->get();
        $provinces = Province::all();

        return view('user.addresses', compact('provinces', 'addresses','order'));
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;



use App\Models\Order;
use App\PaymentGateway\PayStar;
use App\PaymentGateway\Zarinpal;
use Illuminate\Http\Request;

;

class OrderController extends Controller
{

    public function index(){
        $orders =  Order::where(['user_id'=>1])->get();

        return view('user.order',compact('orders'));
    }

    public function show(Order $order){
        return view('user.order_details',compact('order'));
    }
    public function pay(Order $order,Request $request){

        $request->validate([
            'card_number'=>'required|numeric|digits:16',
            'address'=>'required',
        ]);
        $order->update(['address_id'=>$request->address,'card_number'=>$request->card_number]);
        $payStarGateway = new PayStar();
        $payStarGatewayResult = $payStarGateway->send($order, 'پرداخت سفارش');
        return redirect()->to($payStarGatewayResult['success']);
    }

    public function verify(Request $request,Order $order){
        $payStarGateway = new PayStar();
        $payStarGatewayResult = $payStarGateway->verify($request);

        if (array_key_exists('error', $payStarGatewayResult)) {
            return view('user.verify',['msg'=>$payStarGatewayResult['error']]);
           // return redirect()->route('user.payment_verify',['msg'=>$payStarGatewayResult['error']]);
        } else {
            return view('user.verify',['msg'=>$payStarGatewayResult['success']]);
         //   return redirect()->route('user.payment_verify',['msg'=>$payStarGatewayResult['success']]);
        }
    }
}

resources/views/errors.blade.php
@if (count($errors) > 0)
<div class="alert alert-danger">
    <ul class="mb-0">
        @foreach($errors->all() as $error)
            <li class="alert-text">{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/home.blade.php
@extends('layouts.app')
@section('content')

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content=" width=device-width, initial-scale=1"/>
    <!-- TITLE -->
    <title>paystar</title>
    <!-- BOOTSTRAP CSS -->
    <link rel="stylesheet" href="{{asset('css/bootstrap.rtl.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{asset('css/main.css')}}">

</head>

<body>
@include('section.header')
<div class="container  mt-5">
    @yield('content')
</div>
</body>

</html>

resources/views/section/header.blade.php
<div class="header">
    <header>
        <div class="container">
            <div class="d-flex">
                <div class="col-2">
                    <img width="50"  src="{{asset('images/logo.png')}}">
                </div>
                <div class="col-10 text-end">
                    <a href="{{route('order')}}">
                        <div  class="icon-cart">
                            <i class="fa fa-shopping-cart"></i>
                            <span  class="header-badge cart-items-count">سفارشات</span>
                        </div>
                    </a>

                </div>
            </div>
        </div>
    </header>
</div>

resources/views/user/addresses.blade.php
@extends('layouts.app')
@section('content')
    @include('errors')
    <form method="post" action="{{route('pay',['order'=>$order])}}">
        @csrf
        <div class="row">
            <h3>انتخاب آدرس</h3>
            <hr>
            @foreach ($addresses as $address)

                <div class="col-12 mt-5">
                    <input {{$address->id == $order->address_id ? 'checked':''}} type="radio" name="address" value="{{$address->id}}">

                    <span class="mr-2"> عنوان آدرس : <span> {{ $address->title }}
                                                            </span> </span>
                    {{ $address->address }}
                    <br>
                    <span> استان : {{ $address-> province_name($address->province_id) }} </span>
                    <span> شهر : {{ $address->city_name($address->city_id) }} </span>
                    کدپستی :
                    {{ $address->postal_code }}
                    شماره موبایل :
                    {{ $address->cellphone }}

                </div>
            @endforeach

            <div class="mt-5">
                <span>شماره کارت</span>
                <input type="text" name="card_number">
            </div>
            <p class="mt-5"><b>مبلغ قابل پرداخت:</b><span>     {{ number_format($order->paying_amount) }}
                        تومان</span></p>
            <div class="row">
                <div class="col-12 text-end">
                    <button  class="btn btn-primary"> تایید نهایی</button>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/user/order.blade.php
@extends('layouts.app')
@section('content')
<table class="table table-responsive table-bordered table-light orders">
    <thead>
      <tr>
          <th>وضعیت</th>
          <th>تاریخ</th>
          <th>کد سفارش</th>
          <th>مبلغ</th>
      </tr>
    </thead>
    <tbody>
        @if($orders)
            @foreach($orders as $order)
                <tr onclick="window.location = '{{route('order.details',['order'=>$order])}}'">
                    <td>{{$order->payment_status}}</td>
                    <td>{{verta($order->created_at)->format('%d %B، %Y')}}</td>
                    <td>{{$order->id}}</td>
                    <td>
                        {{ number_format($order->paying_amount) }}
                        تومان
                    </td>
                </tr>
            @endforeach
        @endif
    </tbody>

</table>
@endsection

resources/views/user/order_details.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <table class="table table-bordered table-responsive table-light">
            <thead>
            <tr>
                <th> نام محصول</th>
                <th> فی</th>
                <th> تعداد</th>
                <th> قیمت کل</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($order->orderItems as $item)
                <tr>
                    <td class="product-name"> {{ $item->product->name }}</td>
                    <td class="product-price-cart"><span class="amount">
                                                                {{ number_format($item->price) }}
                                                                تومان
                                                            </span></td>
                    <td class="product-quantity">
                        {{ $item->quantity }}
                    </td>
                    <td class="product-subtotal">
                        {{ number_format($item->price * $item->quantity) }}
                        تومان
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
    @if($order->payment_status != 1)
        <div class="row">
            <div class="col-12 text-end">
                <a href="{{route('addresses.index',['order'=>$order])}}" class="btn btn-primary">ادامه خرید</a>
            </div>
        </div>
    @endif
@endsection

resources/views/user/verify.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <p>{{$msg}}</p>

    </div>

@endsection